name: Function Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f appl-docchat/requirements.txt ]; then pip install -r appl-docchat/requirements.txt; fi
        pip install nltk
        python -m nltk.downloader punkt

    - name: Create .env file
      run: |
        echo "AZURE_OPENAI_API_KEY=${{secrets.AZURE_OPENAI_API_KEY}}" >> .env
        echo "AZURE_OPENAI_LLM_DEPLOYMENT_NAME=${{secrets.AZURE_OPENAI_LLM_DEPLOYMENT_NAME}}" >> .env
        echo "AZURE_OPENAI_ENDPOINT=${{secrets.AZURE_OPENAI_ENDPOINT}}" >> .env
        echo "AZURE_OPENAI_EMB_DEPLOYMENT_NAME=${{secrets.AZURE_OPENAI_EMB_DEPLOYMENT_NAME}}" >> .env
        cat .env

    - name: Run tests
      run: |
        cd appl-docchat
        mv settings_template.py settings.py
        pytest