name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # default python in ubuntu-latest is currently 3.10, we want 3.11
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
            run: |
              python -m unittest discover

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install autopep8
        run: pip install autopep8

      - name: Run formatter
        run: autopep8 --max-line-length 100 -a -a --exit-code --diff --recursive timer